---
title: "Biehler et al"
author: "Tricia"
date: "`r Sys.Date()`"
output: pdf_document
---

# load libraries
```{r message=FALSE}
library(ggplot2)
library(dplyr)
library(betareg)
library(emmeans)
```

# Import CSV
```{r}
data <- read.csv("../datafiles/BiehlerDataBKA.csv", header = TRUE, sep = ",")

# Convert 'Sex', 'Month', 'Year', and 'Species' to factors
data$Sex <- factor(data$Sex)
data$Species <- factor(data$Species)
data$Year <- factor(data$Year)
data$Month <- factor(data$Month)
```

# Mean and Standard Devation for BKA
```{r}
# Calculate mean and SD for each species
summary_stats <- data %>%
  group_by(Species) %>%
  summarise(
    Mean = mean(Bacterial_Killing_Percentage, na.rm = TRUE),
    SD = sd(Bacterial_Killing_Percentage, na.rm = TRUE)     
  )

# Print the summary statistics
print(summary_stats)
```

# Transformation of data
```{r}
# Convert percentage to proportion
data$Bacterial_Killing_Proportion <- data$Bacterial_Killing_Percentage / 100

# Apply arcsine square root transformation
data$Bacterial_Killing_Arcsine <- asin(sqrt(data$Bacterial_Killing_Proportion))

# Shapiro-Wilk test for normality
shapiro.test(data$Bacterial_Killing_Arcsine)

# Visual inspection with histogram and Q-Q plot
hist(data$Bacterial_Killing_Arcsine, main="Histogram of Arcsine Transformed Data", xlab="Arcsine Transformed Values")
qqnorm(data$Bacterial_Killing_Arcsine)
qqline(data$Bacterial_Killing_Arcsine, col="blue")
```

Beta regression as data are not normally distributed after arcsin transformation
```{r}
# Fit a beta regression model for the proportion data
beta_bka_species <- betareg(Bacterial_Killing_Proportion ~ Species, data = data)

# View the summary of the model
summary(beta_bka_species)
```
# Post Hoc Comparison
```{r}
# Obtain estimated marginal means for Species from the beta regression model
emmeans_species <- emmeans(beta_bka_species, ~ Species)

# Perform pairwise comparisons between all species
pairwise_comparisons <- pairs(emmeans_species, adjust = "fdr") 

# Print pairwise comparisons with more significant digits
print(pairwise_comparisons)

# Convert pairwise comparisons to a data frame
pairwise_results_df <- as.data.frame(pairwise_comparisons)

# View the results
pairwise_results_df
```

# Model Testing
```{r}
# Fit a model with main effects only
main_effects_model <- betareg(Bacterial_Killing_Proportion ~ Species + Sex + Year + Season, data = data)
model_A <- betareg(Bacterial_Killing_Proportion ~ Species + Season, data = data)
model_B <- betareg(Bacterial_Killing_Proportion ~ Species + Year, data = data)
model_C <- betareg(Bacterial_Killing_Proportion ~ Species + Sex * Season + Year, data = data)
model_D <- betareg(Bacterial_Killing_Proportion ~ Species + Season + Year, data = data)
model_E <- betareg(Bacterial_Killing_Proportion ~ Species, data = data)
model_F <- betareg(Bacterial_Killing_Proportion ~ Species * Sex + Year, data = data)
model_G <- betareg(Bacterial_Killing_Proportion ~ Species * Sex + Season, data = data)
model_H <- betareg(Bacterial_Killing_Proportion ~ Species + Sex * Season, data = data)
model_I <- betareg(Bacterial_Killing_Proportion ~ Species + Sex * Year, data = data)
model_J <- betareg(Bacterial_Killing_Proportion ~ Sex, data = data)
model_K <- betareg(Bacterial_Killing_Proportion ~ Year, data = data)
model_L <- betareg(Bacterial_Killing_Proportion ~ Season, data = data)
# Example for comparing models using AIC
AIC(main_effects_model, model_A, model_B, model_C, model_D, model_E, model_F, model_G, model_H, model_I, model_J, model_K, model_L)
```

# Summarize AIC models
```{r}
summary(main_effects_model)
summary(model_A)
summary(model_B)
summary(model_C)
summary(model_D)
summary(model_E)
summary(model_F)
summary(model_G)
summary(model_H)
summary(model_I)
summary(model_J)
summary(model_K)
summary(model_L)
```

# Boxplot of BKA
```{r warning=FALSE}
# Reorder the species factor levels
data$Species <- factor(data$Species, levels = c("AMGO", "LEGO", "PISI", "HOFI"))

# Create box plot with individual points
BKAAssay <- ggplot(data, aes(x=Species, y=Bacterial_Killing_Percentage)) +
  geom_boxplot(color="black", alpha=0.7) +  # Box plot
  geom_jitter(width=0.2, size=1.5, alpha=0.5) +  # Jittered points
  labs(x="Species",
        y=expression("% " * italic(Salmonella) * " Killed")) +
  scale_y_continuous(limits = c(0, 100), breaks = seq(0, 100, by = 20))  +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size = 15),
    axis.title.x = element_text(size = 15),
    axis.title.y = element_text(size = 15),
    axis.text.x = element_text(size = 12),  # Bold x-axis labels
    axis.text.y = element_text(size = 12)  # Bold y-axis numbers
  )  +
  # Add line for significance between AMGO and HOFI
  geom_segment(aes(x=1, xend=4, y=94, yend=94), color="black", linewidth=.5) +
  # Add text for significance label "***"
  geom_text(aes(x=2.5, y=95, label="***"), color="black", size=5, fontface="bold") +
  # Add line for significance between LEGO and HOFI
  geom_segment(aes(x=2, xend=4, y=88, yend=88), color="black", linewidth=.5) +
  # Add text for significance label "***"
  geom_text(aes(x=3, y=89, label="***"), color="black", size=5, fontface="bold") +
  # Add line for significance between PISI and HOFI
  geom_segment(aes(x=3, xend=4, y=82, yend=82), color="black", linewidth=.5) +
  # Add text for significance label "***"
  geom_text(aes(x=3.5, y=83, label="***"), color="black", size=5, fontface="bold") +
  # Add line for significance between PISI and AMGO
  geom_segment(aes(x=1, xend=3, y=60, yend=60), color="black", linewidth=.5) +
  # Add text for significance label "***"
  geom_text(aes(x=2, y=61, label="***"), color="black", size=5, fontface="bold") +
  # Add line for significance between PISI and LEGO
  geom_segment(aes(x=2, xend=3, y=54, yend=54), color="black", linewidth=.5) +
  # Add text for significance label "***"
  geom_text(aes(x=2.5, y=55, label="***"), color="black", size=5, fontface="bold") +
  # Add line for significance between AMGO and LEGO
  geom_segment(aes(x=1, xend=2, y=48, yend=48), color="black", linewidth=.5) +
  # Add text for significance label "***"
  geom_text(aes(x=1.5, y=50, label="P = 0.37"), color="black", size=3, fontface="bold")

print(BKAAssay)
```
# export tiff with 300dpi
```{r warning=FALSE}
ggsave(
filename="../figures/BKAAssay.tiff",
plot = BKAAssay,
width = 200,
height = 200,
units = c("mm"),
dpi = 300,
bg = "white"
)
```

# Import Growth Curve Data
```{r}
growthcurvedata <- read.csv("../datafiles/GrowthCurve.csv", header = TRUE, sep = ",")
```

# Growth Curve
```{r warning=FALSE}
# Calculate mean absorbance for each time point
average_data <- growthcurvedata %>%
  group_by(Time.h.) %>%
  summarise(
    Mean = mean(A600),
    SD = sd(A600),
    Min = min(A600),
    Max = max(A600)
  )

# Plot with smoothed line and shaded area representing the standard deviation
growthcurve <- ggplot() +
  geom_ribbon(data = average_data, aes(x = Time.h., y = Mean, ymin = Min, ymax = Max), 
              fill = "grey80", alpha = 0.5) +
  geom_smooth(data = average_data, aes(x = Time.h., y = Mean), method = "loess", 
              formula = y ~ x, color = "black", se = FALSE, 
              size = 0.5) +
  geom_point(data = growthcurvedata, aes(x = Time.h., y = A600), color = "black", size = 0.5) + 
  labs(x = "Time of Incubation (h)", 
       y = "Absorbance (600 nm)") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold", size = 10),
    axis.title.x = element_text(face = "bold", size = 10),
    axis.title.y = element_text(face = "bold", size = 10)
  )

print(growthcurve)
```
# print growth curve info
```{r}
print(average_data)
```

# export tiff with 300dpi
```{r warning=FALSE}
ggsave(
filename="../figures/growthcurve.tiff",
plot = growthcurve,
width = 200,
height = 100,
units = c("mm"),
dpi = 300,
bg = "white"
)
```